.PHONY: core create train create+train+decode

all: core create train create+train+decode

core:	
	$(MAKE) -C core

create:	
	$(MAKE) -C create

train:	
	$(MAKE) -C train

create+train+decode:	
	$(MAKE) -C create+train+decode
